Resources:
Ec2Instance:
  Type: 'AWS::EC2::Instance'
  Properties:
    SecurityGroups:
      - !Ref InstanceSecurityGroup
    KeyName: udacity
    # Ubuntu Server 18.04 LTS (HVM), SSD Volume Type
    # Region Availability https://cloud-images.ubuntu.com/locator/ec2/
    ImageId: 'ami-01996625fff6b8fcc'

InstanceSecurityGroup:
  Type: 'AWS::EC2::SecurityGroup'
  Properties:
    GroupDescription: Enable SSH access via port 22
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0