Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  # TODO: Missing inbound 3000 port used for NodeJS application (see Ansible configuration)
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity
      # [eu-north-1] Amazon Linux 2 AMI (HVM), SSD Volume Type
      ImageId: ami-02cb52d7ba9887a93