---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  become: true

- name: Install dependencies
  yum:
    name:
      - nodejs14
      - pm2
    state: present
  become: true

- name: Create directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: Executing node
  shell: |
    pm2 start ~/web/index.js -f