---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  become: true

- name: Fetch NodeJS repository
  shell: |
    curl --silent --location https://rpm.nodesource.com/setup_14.x | bash -
  become: true

- name: Install dependencies
  yum:
    name:
      - nodejs
    state: present
  become: true

- name: Install PM2
  shell: |
    npm i -g pm2

- name: Create directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: Executing node
  shell: |
    pm2 start ~/web/index.js -f