---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install dependencies
  yum:
    name:
      - nodejs
      - npm
      - pm2
    state: present

- name: Create directory
  file:
    path: ~/web
    state: directory

- name: Copy index test page
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: Executing node
  shell: |
    pm2 start ~/web/index.js -f
  become: true