version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: ansible/ansible:ubuntu1404
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["6f:e5:65:23:ad:96:77:2f:c3:cd:08:1d:d2:b8:f9:a6"]
      - run:
          name: Configure server
          command: |
            ansible-playbook ansible/main-remote.yml -i ansible/inventory.ini

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure